version: "3.8"
services:
  credit-risk-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./mlflow.db:/app/mlflow.db # Persist MLflow database
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///mlflow.db
